
export interface StyleDetail {
  name: string;
  description: string;
}

export const TYPOGRAPHY_STYLES = [
  "Bubble Lettering (Graffiti)",
  "Groovy 70s Liquid",
  "Vintage Americana Label",
  "1950s Diner Neon",
  "Victorian Ornamental",
  "Art Deco Gold Geometry",
  "Rubber Hose Cartoon Text",
  "Pixel Art 8-Bit Font",
  "VHS Glitch Text",
  "Chrome Metal Liquid",
  "Inflated Foil Balloon",
  "Melting Slime Drip",
  "Neon Light Tube",
  "Carved Stone/Marble",
  "Organic Moss/Vine Text",
  "Furry/Plush Texture",
  "Translucent Glass/Ice",
  "Volumetric Smoke/Cloud",
  "Edible Candy/Gummy",
  "Lego Brick Text",
  "Cyberpunk HUD Glitch",
  "Swiss International Minimal",
  "Kinetic Motion Blur",
  "Data Matrix Code",
  "Y2K Chrome Aesthetic",
  "Brutalist Bold",
  "Holographic Sticker Text",
  "Ransom Note Cutouts",
  "Heavy Metal Band Logo",
  "Punk Rock Stencil",
  "Dripping Spray Paint",
  "Handwritten Calligraphy",
  "Gothic Blackletter",
  "Elvish Script & Runes",
  "Chalkboard Sketch",
  "Watercolor Brush Stroke"
];

export const STYLE_CATEGORIES: Record<string, StyleDetail[]> = {
  "Studio Extraction": [
    { name: "Subject Extraction (Ultra Fidelity)", description: "Direct visual clone of the reference image. Maintain exact proportions, lighting, and details. Isolate subject on black." }
  ],
  "Avatars & Portraits": [
    { name: "Pixar / Disney 3D", description: "3D render, Redshift engine, subsurface scattering, ambient occlusion, soft rounded features, expressive eyes, cute proportions, studio lighting." },
    { name: "Corporate Memoji 3D", description: "Flat 3D vector style, smooth gradients, soft clay texture, friendly minimal features, vibrant colors, floating elements." },
    { name: "Funko Pop Style", description: "Vinyl plastic texture, oversized square head, black button eyes, small body, rigid pose, collectible toy aesthetic." },
    { name: "Anime Chibi (SD)", description: "Super Deformed proportions, 2-head tall height, giant sparkling eyes, simplified vector details, cel-shaded, kawaii aesthetic." },
    { name: "The Simpsons Yellow", description: "Matt Groening style, specific yellow #FFD90F skin tone, overbite, tubular limbs, thick uniform black outlines, flat colors." },
    { name: "Rubber Hose (1930s)", description: "Fleischer Studios style, black and white ink, pie-cut eyes, noodle limbs, white gloves, bouncing rhythm, film grain texture." },
    { name: "South Park Cutout", description: "Construction paper texture, imperfect cut edges, geometric simple shapes, flat lighting, stop-motion aesthetic." },
    { name: "Rick & Morty Sci-Fi", description: "Thin shaky ink lines, squiggly pupils, flat coloring, specific color palette (muted greens/blues), adult swim animation style." },
    { name: "Animal Crossing Villager", description: "Soft felt/flock texture, round spherical head, no nose, tiny limbs, pastel colors, cozy nintendo aesthetic." },
    { name: "Lego Minifigure", description: "Shiny ABS plastic texture, C-clamp hands, cylindrical yellow head, blocky torso, stud connections." },
    { name: "Peanuts / Charlie Brown", description: "Wobbly ink quill lines, minimal dots for eyes, oversized round heads, newspaper comic strip texture." },
    { name: "Scott Pilgrim Comic", description: "Bryan Lee O'Malley style, bold thick outlines, expressive indie comic features, vibrant flat colors, video game influence." },
    { name: "Gorillaz Vector", description: "Jamie Hewlett style, gritty urban vector, zombie-fied features, heavy shadows, unique coloring, punk aesthetic." },
    { name: "Adventure Time", description: "Pendleton Ward style, noodle arms, dot eyes, no outlines on color changes, vibrant candy colors, surreal fantasy." },
    { name: "Muppet / Puppet", description: "Fuzzy felt fabric texture, visible seams, ping-pong ball eyes, foam structure, depth of field photography look." }
  ],
  "Paper-Kissed": [
    { name: "Pen Pals: Air Mail Kit", description: "Vintage envelope texture, red and blue parallelogram border stripes, cancellation ink stamps, faded paper." },
    { name: "Pen Pals: Junk Journal Ephemera", description: "Layered mixed media collage, torn paper edges, coffee stains, ticket stubs, washi tape overlays." },
    { name: "Pen Pals: Cottage Correspondence", description: "Creamy parchment texture, dried pressed flowers, wax seal aesthetic, botanical sketches, soft pastels." },
    { name: "Pen Pals: Typewriter Notes", description: "Rough pulp paper texture, courier font, uneven ink dispersion, minimalist layout, typewriter ribbon aesthetic." },
    { name: "Pen Pals: Traveler’s Postcards", description: "Worn cardboard texture, vintage travel postmarks, scenic illustration, slightly distressed edges." },
    { name: "Lace Border: Victorian Doily Frames", description: "Intricate laser-cut paper lace, white doily texture, complex geometric floral patterns, antique vibe." },
    { name: "Lace Border: Bridal Lace Minimal", description: "Sheer white lace fabric texture, delicate transparency, soft shadows, elegant floral embroidery." },
    { name: "Lace Border: Sweetheart Scallops", description: "Cute rounded scalloped paper edges, pastel pinks and whites, bakery box aesthetic." },
    { name: "Lace Border: Goth Lace", description: "Black lace netting texture, victorian gothic patterns, spiderweb motifs, dark romantic aesthetic." },
    { name: "Lace Border: Tea Stain Lace", description: "Aged yellowed lace, antique fabric texture, grunge overlay, vintage heirloom look." },
    { name: "Cozy Bookish: Tea & Chapters", description: "Warm autumn color palette, watercolor illustration, steaming mugs, stacked books, cozy atmosphere." },
    { name: "Cozy Bookish: Library Day", description: "Dark academia aesthetic, wooden textures, leather-bound books, dust motes, warm lamp lighting." },
    { name: "Cozy Bookish: Botanical Reading Nook", description: "Indoor plants, open books, line art illustration, calming greens and browns, peaceful vibe." },
    { name: "Cozy Bookish: Rainy Window Reads", description: "Blue-grey moody palette, rain droplets on glass effect, soft blur, blankets and books." },
    { name: "Cozy Bookish: Spooky Bookish", description: "Grimoires, skulls, melting candles, dark purple and orange tones, witchy academia." }
  ],
  "Tattoo Parlor": [
    { name: "American Traditional (Old School)", description: "Sailor Jerry style, bold thick uniform black outlines, limited primary palette (red, yellow, green, black), minimal shading." },
    { name: "Neo-Traditional (Bold Lines)", description: "Art Nouveau influence, varying line weights, lush sophisticated color palette, floral framing, illustrated realism." },
    { name: "Japanese Irezumi (Dragon/Koi)", description: "Ukiyo-e woodblock influence, wind bars (finger waves), cherry blossoms, flowing composition, scales texture." },
    { name: "Trash Polka (Red/Black Chaos)", description: "High contrast collage style, realistic portraits mixed with abstract red and black brushstrokes, text overlays, chaotic composition." },
    { name: "Blackwork / Stipple Shading", description: "Solid heavy black ink, negative space shapes, stipple dot shading (dotwork), high contrast, geometric patterns." },
    { name: "Stick and Poke (Rough)", description: "Ignorant style, shaky imperfect lines, naive drawing, doodle aesthetic, prison tattoo vibe." },
    { name: "Watercolor Tattoo Style", description: "No outlines, vibrant bleeding color washes, paint splatter effects, soft gradients, artistic painterly look." },
    { name: "New School (Graffiti Cartoon)", description: "Exaggerated caricature proportions, fisheye perspective, vibrant neon bubblegum colors, graffiti influence." },
    { name: "Tribal / Polynesian", description: "Solid black ink, sharp geometric patterns, maori/samoan motifs, flowing muscle-contouring shapes." },
    { name: "Geometric Dotwork", description: "Sacred geometry, mandalas, pointillism, mathematical precision, strictly black and white dots." },
    { name: "Chicano Black & Grey", description: "Fine line realism, smooth gray shading, script lettering, clowns/religious iconography, airbrush feel." },
    { name: "Minimalist Fine Line", description: "Single needle technique, extremely thin delicate lines, minimal detail, elegant and subtle." },
    { name: "Sailor Jerry Style", description: "Specific vintage 1940s flash, pin-ups, swallows, anchors, hearts with banners, distressed paper background." },
    { name: "Bio-Mechanical", description: "H.R. Giger influence, torn flesh revealing gears and pistons, metallic textures, high contrast shading." },
    { name: "Ignorant Style (Sketchy)", description: "Intentionally bad drawing, scribbles, childish handwriting, ironic humor, dry humor." }
  ],
  "Fine Art Masters": [
    { name: "Vincent Van Gogh (Impressionist)", description: "Thick impasto oil paint texture, visible swirling brushstrokes, vibrant yellow and blue palette, starry night influence." },
    { name: "Salvador Dali (Surrealism)", description: "Photorealistic rendering of impossible objects, melting clocks, dreamscapes, elongated limbs, desert lighting." },
    { name: "Pablo Picasso (Cubism)", description: "Fragmented geometric shapes, multiple perspectives simultaneously, flat planes of color, abstract portraiture." },
    { name: "Gustav Klimt (Gold Leaf)", description: "Byzantine mosaic influence, heavy use of metallic gold leaf texture, decorative swirling patterns, erotic elegance." },
    { name: "Frida Kahlo (Folk Surrealism)", description: "Naïve folk art style, vibrant tropical colors, monkeys/parrots, floral headbands, unibrow self-portraiture." },
    { name: "Andy Warhol (Pop Art)", description: "Silk screen print texture, misaligned registration, high contrast neon colors, repetitive imagery, celebrity culture." },
    { name: "Jean-Michel Basquiat (Neo-Expressionism)", description: "Raw primitive scribbles, oil stick texture, crowns, skulls, anatomy diagrams, chaotic composition, graffiti roots." },
    { name: "Keith Haring (Street Pop)", description: "Bold thick continuous black lines, vibrant solid fill colors, kinetic action lines, dancing figures, barking dogs." },
    { name: "Hokusai (Ukiyo-e Woodblock)", description: "Japanese woodblock print texture, prussian blue, flat perspective, crashing waves, Mt Fuji, traditional ink outline." },
    { name: "Alphonse Mucha (Art Nouveau)", description: "Organic flowing lines, whiplash curves, floral halos, pastel colors, elegant female figures, poster design." },
    { name: "M.C. Escher (Impossible Geometry)", description: "Lithograph print texture, mathematical tessellations, impossible architecture, metamorphosis, black and white." },
    { name: "René Magritte (Surrealism)", description: "Deadpan realism, bowler hats, green apples, blue sky with clouds, visual puns, clean painting style." },
    { name: "Banksy (Stencil Graffiti)", description: "Multi-layer stencil aesthetic, black spray paint texture, concrete background elements, satirical, red balloon accents." },
    { name: "Edward Hopper (Americana)", description: "Cinematic lighting, strong shadows, isolation, urban realism, muted color palette, nighthawks vibe." },
    { name: "Hieronymus Bosch (Chaos)", description: "Early Netherlandish style, fantastical creatures, hybrid beasts, crowded scenes, weird surrealism, oil on oak panel." }
  ],
  "Architecture & Design": [
    { name: "Mid-Century Modern (Eames)", description: "1950s aesthetic, atomic shapes, teak wood texture, olive and orange tones, clean lines, organic curves." },
    { name: "Brutalist Concrete", description: "Raw concrete (béton brut) texture, massive geometric blocky forms, monochromatic grey, imposing structures." },
    { name: "Art Deco (Gatsby Style)", description: "1920s luxury, gold and black palette, sunburst motifs, geometric symmetry, metallic gradients, sleek elegance." },
    { name: "Bauhaus (Geometric)", description: "Form follows function, primary colors (red, blue, yellow), simple geometric shapes (circle, square, triangle), industrial design." },
    { name: "Memphis Group (80s Squiggles)", description: "Postmodern 80s, black and white geometric patterns, bright pastel colors, bacteria squiggles, plastic laminate texture." },
    { name: "Industrial Loft (Brick/Pipe)", description: "Exposed red brick texture, black iron piping, edison bulbs, copper accents, utilitarian aesthetic." },
    { name: "Gothic Cathedral", description: "Pointed arches, flying buttresses, stained glass texture, stone gargoyles, verticality, intricate stone carving." },
    { name: "Cyberpunk Cityscape", description: "Neon sign lighting, rain-slicked wet streets, towering skyscrapers, holographic ads, blue and pink color grading." },
    { name: "Isometric Room Cutaway", description: "Orthographic projection, low poly 3D, cutaway diorama, clean vector lighting, mini-world aesthetic." },
    { name: "Blueprint / Schematic", description: "Cyanotype blue background, white technical architectural lines, measurements, grid overlay, technical drawing." },
    { name: "Swiss International Style", description: "Grid-based layout, Helvetica typography, asymmetric organization, negative space, objective photography." },
    { name: "Victorian Ornamentation", description: "William Morris wallpaper patterns, damask texture, intricate floral flourishes, serif typography, horror vacui." },
    { name: "Futuristic Zaha Hadid", description: "Parametric design, fluid sweeping curves, white glossy materials, organic architecture, futuristic forms." },
    { name: "Japanese Zen Garden", description: "Raked sand patterns, arranged stones, moss textures, bonsai trees, minimalism, asymmetry." },
    { name: "Tiki Bar Aesthetic", description: "Bamboo texture, carved wooden masks, tropical thatch, Polynesian pop style, warm fire lighting." }
  ],
  "Esoteric & Occult": [
    { name: "Tarot Card (Rider-Waite)", description: "Pamela Colman Smith style, heavy black ink outlines, flat matte colors, yellow backgrounds, symbolic stage imagery." },
    { name: "Alchemical Illustration", description: "17th century copperplate engraving, sun and moon motifs, latin text, hermetic symbols, strange chimeras." },
    { name: "Zodiac / Astrology Wheel", description: "Celestial map, constellations, horoscope symbols, midnight blue and gold palette, star charts." },
    { name: "Sacred Geometry", description: "Flower of life patterns, metatron's cube, golden ratio, vector line art, mathematical precision, thin lines." },
    { name: "Palmistry Hand Map", description: "Vintage medical illustration, hand diagram with labeled lines (heart line, head line), aged paper texture." },
    { name: "Ouija Board Aesthetic", description: "Victorian parlor game style, ornate typography, sun and moon corners, planchette icon, wood grain texture." },
    { name: "Masonic Symbols", description: "Eye of providence, square and compass, checkerboard floor, stone texture, secret society vibes." },
    { name: "Vintage Magic Poster", description: "Late 19th century lithograph, red devils, floating women, bold yellow typography, distressed paper edges." },
    { name: "Grimoire Spellbook Page", description: "Handwritten ink quill text, botanical ingredient sketches, ink blots, burnt paper edges, coffee stains." },
    { name: "Crystal Healing", description: "Watercolor crystal illustration, geometric facets, aura gradients, quartz and amethyst textures." },
    { name: "Third Eye / Chakra", description: "Psychedelic spiritual art, meditating silhouette, lotus flower, rainbow gradient energy centers, glowing aura." },
    { name: "Illuminati Eye", description: "Triangle with eye, conspiracy theory aesthetic, dollar bill engraving style, novus ordo seclorum." },
    { name: "Runes & Norse Magic", description: "Carved stone texture, elder futhark runes, viking knotwork patterns, weathered grey stone." },
    { name: "Witchcraft / Potion Label", description: "Aged apothecary labels, 'Eye of Newt', vintage typography, glass bottle illustration, halloween vibe." },
    { name: "Day of the Dead Sugar Skull", description: "Mexican Calavera style, intricate floral patterns on skull, bright marigold and teal colors, festive." }
  ],
  "Mixology & Beverages": [
    { name: "Tiki Cocktail (Mai Tai)", description: "Ceramic tiki mug texture, elaborate fruit garnishes, umbrellas, tropical flowers, exotic saturated colors." },
    { name: "Craft Beer Can Label", description: "Hipster vector illustration, bold sans-serif typography, hop cones, flat colors, modern microbrewery style." },
    { name: "Vintage Whiskey Label", description: "Ornate victorian border, serif typography, gold foil stamping effect, aged beige background, dignified look." },
    { name: "Latte Art (Coffee)", description: "Top-down view coffee cup, brown crema, white foam heart/rosetta pattern, ceramic saucer texture." },
    { name: "Neon Bar Sign", description: "Glowing bent glass tube effect, dark brick background, vibrant electric colors (pink/blue), light bloom." },
    { name: "Martini Art Deco", description: "Sleek geometric glass shape, olive garnish, 1920s glamour, gold and black palette, elegant lines." },
    { name: "Wine Bottle Label", description: "Etched chateau illustration, cursive script, cream paper texture, grape vines, classic luxury." },
    { name: "Soda Pop 50s Ad", description: "Retro advertising illustration, smiling mascot, condensation on glass bottle, cherry red colors, wholesome vibe." },
    { name: "Bubble Tea (Boba)", description: "Kawaii illustration, pastel milk tea color, black tapioca pearls at bottom, fat straw, cute face." },
    { name: "Energy Drink (Aggressive)", description: "Sharp angular vector shapes, lightning bolts, claws, lime green and black, extreme sports aesthetic." },
    { name: "Teacup (Alice in Wonderland)", description: "Stacked mismatched porcelain cups, mad hatter style, spilling tea, whimsical illustration." },
    { name: "Oktoberfest Stein", description: "Dimpled glass beer mug, golden beer liquid, overflowing white foam, pretzel accompaniment." },
    { name: "Champagne Celebration", description: "Exploding cork, spraying liquid, golden bubbles, festive sparkles, elegant flute glass." },
    { name: "Juice Box (Kawaii)", description: "Square carton shape, cute fruit mascot character, bendy straw, bright primary colors." },
    { name: "Speakeasy Menu Art", description: "Prohibition era style, art deco frame, dark moody background, gold metallic text, secret society vibe." }
  ],
  "Music & Sound": [
    { name: "Heavy Metal Album Cover", description: "Ed Repka style, chrome logo, skeletons, lightning, toxic green and purple, thrash metal aesthetic." },
    { name: "Psychedelic Rock Poster (60s)", description: "Wes Wilson style, warping melted typography, vibrating complementary colors (red/green), fillmore poster." },
    { name: "Synthwave / Retrowave Cover", description: "80s computer grid, neon sun setting, chrome typography, palm trees, purple and magenta gradient." },
    { name: "Jazz Club (Blue Note Style)", description: "Reid Miles design, duotone photography, bold clean typography, cool blue palette, cropped composition." },
    { name: "Punk Rock Zine Xerox", description: "High contrast black and white photocopy texture, cut-and-paste ransom notes, safety pins, grime." },
    { name: "Techno / Glitch Art", description: "Datamoshing effect, RGB color split, digital noise, abstract geometric shapes, futuristic aesthetic." },
    { name: "Lo-Fi Hip Hop Anime", description: "Soft anime aesthetic, sunset lighting, cozy room, headphones, pastel color palette, nostalgia." },
    { name: "Vintage Vinyl Record", description: "Black grooved vinyl texture, colorful center label, light reflection on grooves, spinning motion." },
    { name: "Cassette Tape Aesthetic", description: "Transparent plastic texture, spools of tape, handwritten label, 80s analog vibe." },
    { name: "Boombox / Ghetto Blaster", description: "Chrome speakers, buttons and dials, 80s street culture, graffiti background elements." },
    { name: "Moduluar Synthesizer", description: "Patch cables, knobs, blinking LEDs, wood side panels, technical interface." },
    { name: "Daft Punk Robot Style", description: "Chrome and Gold robot helmets, LED visor displays, leather jackets, sleek sci-fi disco." },
    { name: "Gorillaz Style", description: "Jamie Hewlett vector art, zombie skin tones, heavy outlines, urban streetwear, unique shading." },
    { name: "K-Pop Pastel Aesthetic", description: "Soft dreamy filter, hearts, stars, pastel pinks and blues, polished fashion, cute stickers." },
    { name: "Country Western Poster", description: "Hatch show print style, wood type font, cowboy silhouette, distressed paper, western border." }
  ],
  "Street Art & Urban": [
    { name: "Graffiti Wildstyle", description: "Complex interlocking letters, arrows, drips, 3D block effects, vibrant spray paint colors, illegible to laymen." },
    { name: "Wheatpaste Poster", description: "Wrinkled paper texture, glue residue, black and white high contrast image, peeling edges, urban wall background." },
    { name: "Sticker Bomb Collage", description: "Overlapping chaos of various sticker styles, logos, characters, creating a dense pattern." },
    { name: "Stenciled Spray Paint", description: "Banksy style, single layer black stencil, overspray mist, cardboard or concrete texture background." },
    { name: "Dripping Marker Tag", description: "Chisel tip marker stroke, ink drips, handstyle signature, street vandalism aesthetic." },
    { name: "Skateboard Deck Art", description: "Screen printed graphic, ply wood grain showing through, edgy illustration, skulls/demons/cartoons." },
    { name: "Subway Map Aesthetic", description: "Vignelli design, colorful connecting lines, station dots, clean white background, transit graphic design." },
    { name: "Urban Decay / Grunge", description: "Peeling paint, rust texture, dirt, grime, cracked concrete, muted desaturated colors." },
    { name: "Sneakerhead Culture", description: "Vector illustration of iconic shoes (Jordan 1s), clean lines, flat colors, focus on shoe anatomy." },
    { name: "Hypebeast Brand Logo", description: "Supreme style, red box logo, minimalist typography, luxury meets street, bold branding." },
    { name: "Lowrider Car Art", description: "Airbrushed mural style, chrome details, pinstriping, candy paint colors, chicano culture influence." },
    { name: "Neon City Night", description: "Cyberpunk urban photography, wet pavement reflections, glowing neon signs, rainy atmosphere." },
    { name: "Pixelated Street Art (Invader)", description: "Mosaic tile texture, 8-bit space invader characters, cemented onto wall, guerrilla art." },
    { name: "Chalk Sidewalk Art", description: "Pastel chalk texture, rough pavement background, anamorphic 3D illusion, dusty look." },
    { name: "Muralism (Realistic)", description: "Large scale spray paint portraiture, vibrant colors, shading with spray can texture, public art." }
  ],
  "Sci-Fi & Cybernetics": [
    { name: "Cyberpunk 2077 (High Tech Low Life)", description: "Cybernetic implants, neon lights, gritty texture, facial interface lines, futuristic punk fashion." },
    { name: "Retro Futurism (Raygun Gothic)", description: "1950s vision of future, chrome fins, bubble helmets, atompunk, flying cars, optimistic aesthetic." },
    { name: "H.R. Giger (Biomech)", description: "Monochromatic grey, organic shapes blended with industrial pipes, ribbed textures, xenomorph aesthetic." },
    { name: "NASA Space Suit (Realistic)", description: "White fabric texture, gold reflective visor, life support pack, patches, realistic lighting." },
    { name: "Mecha / Gundam Robot", description: "Angular armor plating, panel lines, warning decals, giant robot scale, pristine metal." },
    { name: "Matrix Digital Rain", description: "Falling green code characters, black background, digital glow, hacker terminal aesthetic." },
    { name: "Terminator Chrome Skeleton", description: "Polished endoskeleton, red glowing eyes, hydraulic pistons, metallic reflections." },
    { name: "Star Wars Droid", description: "Used universe aesthetic, weathering, oil stains, exposed wires, panels, industrial design." },
    { name: "Star Trek LCARS Interface", description: "Okudagram, flat geometric UI, rounded corners, pastel orange and purple on black, technical display." },
    { name: "Alien Grey / UFO", description: "Classic big black eyes, smooth grey skin, flying saucer, eerie lighting, x-files aesthetic." },
    { name: "Post-Apocalyptic (Mad Max)", description: "Rusted metal, dust, leather straps, spikes, improvised weapons, desert wasteland palette." },
    { name: "Steampunk Brass & Gears", description: "Victorian technology, brass and copper textures, clockwork gears, steam pipes, goggles, leather." },
    { name: "Dieselpunk (WWII Tech)", description: "Heavy steel plating, rivets, oil smoke, 1940s industrial military aesthetic, grime." },
    { name: "Synthwave Grid", description: "Perspective wireframe grid, purple landscape, retro sun, horizon line, 80s CGI look." },
    { name: "Holographic UI", description: "Translucent blue light, floating screens, data visualizations, scanlines, futuristic interface." }
  ],
  "Fantasy & RPG": [
    { name: "Dungeons & Dragons Oil Paint", description: "Keith Parkinson/Larry Elmore style, realistic oil painting, dramatic lighting, epic high fantasy." },
    { name: "Magic The Gathering Card", description: "Detailed digital painting, dynamic composition, magical effects, fantasy creature portrait." },
    { name: "World of Warcraft Hand Painted", description: "Blizzard style, chunky stylized proportions, hand-painted texture, bold colors, oversized weapons." },
    { name: "Elden Ring Dark Fantasy", description: "FromSoftware aesthetic, gold and rot color palette, intricate armor, decay, epic scale, gloomy atmosphere." },
    { name: "Tolkien Map Style", description: "Middle Earth cartography, ink on aged parchment, hand drawn mountains and trees, calligraphy labels." },
    { name: "Middle Earth Illustration", description: "Alan Lee style, pencil and watercolor, ethereal atmosphere, delicate details, muted earth tones." },
    { name: "Final Fantasy Concept Art", description: "Yoshitaka Amano style, delicate wispy lines, watercolor washes, ethereal characters, dreamlike." },
    { name: "Pixel RPG (16-bit)", description: "SNES era sprite art, limited color palette, clean pixel clusters, top-down perspective." },
    { name: "Anime Fantasy (Ghibli)", description: "Kazuo Oga style backgrounds, lush painted nature, cute spirits, watercolor feel, peaceful." },
    { name: "Medieval Bestiary Sketch", description: "Historical manuscript style, bizarre animal anatomy, ink doodles, parchment background." },
    { name: "Stained Glass Window", description: "Mosaic of colored glass, thick black lead lines, glowing light transmission, religious/regal pose." },
    { name: "Dragon Scale Texture", description: "Closeup of reptilian armor, iridescent shimmer, overlapping scales, detailed texture." },
    { name: "Potion Bottle", description: "Glass bottle with cork, glowing liquid inside, bubbles, magical aura." },
    { name: "Mimic Chest", description: "Treasure chest with monster teeth and tongue, wood and gold texture, trap." },
    { name: "Necromancer Skull", description: "Human skull with glowing green magic eyes, dark aura, bone texture." },
    { name: "Druid / Nature Magic", description: "Glowing runes, entangled vines, leaves, wooden staff, organic magic." }
  ],
  "Horror & Macabre": [
    { name: "Lovecraftian Eldritch Horror", description: "Unknowable geometry, tentacles, many eyes, cosmic madness, dark slime textures." },
    { name: "Junji Ito (Body Horror Manga)", description: "Detailed black and white line art, spirals, grotesque distortions, shading lines, disturbing surrealism." },
    { name: "Vintage Horror Comic", description: "Tales from the Crypt style, four-color printing process, halftones, shock expression, pulp paper." },
    { name: "Vintage Thriller Poster", description: "1970s movie poster style, airbrushed, floating heads, screaming face, high drama." },
    { name: "Zombie Survival", description: "Rotting flesh texture, torn clothes, gore, vacant eyes, gritty dirty aesthetic." },
    { name: "Tim Burton Gothic", description: "German expressionism influence, spindly shapes, stripes, spirals, dark sunken eyes, pale skin." },
    { name: "Creepy Doll / Annabelle", description: "Cracked porcelain texture, glass eyes, victorian dress, uncanny valley." },
    { name: "Ghost / Spirit Photography", description: "Double exposure, motion blur, translucent figures, sepia tone, victorian haunting." },
    { name: "Vampire / Dracula Aesthetic", description: "Bela Lugosi style, black cape, red velvet, fangs, slicked hair, gothic elegance." },
    { name: "Werewolf Transformation", description: "Mid-transformation, fur texture, claws, yellow eyes, snarling mouth." },
    { name: "Serial Killer Ransom Note", description: "Letters cut from magazines and pasted together, chaotic layout, threatening vibe." },
    { name: "Red Ink Splatter Art", description: "Ralph Steadman style, chaotic ink splashes, drippy lines, aggressive energy, blood red." },
    { name: "X-Ray Skeleton", description: "Inverted black and white, transparent anatomy, bone structure, medical imaging look." },
    { name: "Plague Doctor Mask", description: "Leather beak mask, goggles, black hat, dark ominous figure." },
    { name: "Cursed Object", description: "Antique item, monkey paw or doll, surrounded by dark aura, sinister lighting." }
  ],
  "Animation & Cartoons": [
    { name: "Pixar 3D Style", description: "RenderMan engine, soft area lighting, subsurface scattering, appealing character design, high detail." },
    { name: "Disney Renaissance 2D", description: "1990s Disney style, clean ink lines, fluid animation poses, cel shading, expressive faces." },
    { name: "Rubber Hose (1930s Mickey)", description: "Steamboat Willie style, black and white, pie eyes, gloves, noodle limbs, bouncing rhythm." },
    { name: "Looney Tunes Classic", description: "Chuck Jones style, flat painted backgrounds, slapstick poses, expressive eyes." },
    { name: "SpongeBob Style", description: "Thick varying outline, gross-up closeups, watercolor backgrounds, specific color palette." },
    { name: "The Simpsons Style", description: "Yellow skin, overbite, tubular hair, specific eyes, flat colors, thick outlines." },
    { name: "Rick and Morty Style", description: "Squiggly pupils, drool, thin shaky lines, sci-fi gadgets, flat coloring." },
    { name: "Adventure Time Style", description: "Noodle arms, dot eyes, simple shapes, pastel candy colors, no outline on color changes." },
    { name: "South Park Paper Cutout", description: "Construction paper texture, simple geometric shapes, flat lighting, stop motion feel." },
    { name: "Spider-Verse Halftone", description: "3D mixed with 2D, chromatic aberration, halftone dots, line hatching, frame rate drop style." },
    { name: "Anime Shonen (Action)", description: "Dynamic angles, speed lines, spiky hair, intense expressions, cel shaded." },
    { name: "Anime Shojo (Sparkly)", description: "Big eyes with many highlights, flowery backgrounds, soft focus, romantic aesthetic." },
    { name: "Studio Ghibli Background", description: "Kazuo Oga style, poster paint texture, detailed clouds and nature, peaceful atmosphere." },
    { name: "Hanna-Barbera (Scooby Doo)", description: "Limited animation style, simple walk cycles, neckwear (ascots/collars), flat backgrounds." },
    { name: "Stop Motion (Laika)", description: "Clay or 3D printed texture, physical lighting, depth of field, tactile feel." }
  ],
  "Comics & Graphic Novels": [
    { name: "Marvel Modern Superhero", description: "Digital coloring, dynamic foreshortening, muscle definition, cinematic lighting, glossy finish." },
    { name: "DC Dark Knight Noir", description: "Heavy use of shadows (chiaroscuro), gritty realism, rain, muted colors, detective vibe." },
    { name: "Frank Miller (Sin City)", description: "High contrast pure black and white, no greys, negative space composition, splash of red." },
    { name: "Jack Kirby (Retro Dots)", description: "Kirby crackle energy dots, blocky technology, dynamic poses, bold lines, 60s color palette." },
    { name: "Mike Mignola (Hellboy)", description: "Angular shapes, heavy black shadows, flat colors, skull motifs, gothic architecture." },
    { name: "Watchmen Style", description: "Dave Gibbons style, 9-panel grid influence, realistic coloring, detailed backgrounds." },
    { name: "The Walking Dead (B&W)", description: "Tony Moore/Charlie Adlard style, grey wash tones, grit texture, zombies, dirty aesthetic." },
    { name: "Tintin (Ligne Claire)", description: "Hergé style, clear line, uniform line weight, flat colors, no hatching/shading, legible." },
    { name: "Peanuts (Charles Schulz)", description: "Minimalist ink lines, wobbly stroke, large heads, simple dots for eyes." },
    { name: "Calvin & Hobbes Watercolor", description: "Bill Watterson style, expressive ink brush lines, beautiful watercolor scenery." },
    { name: "Garfield Sunday Strip", description: "Jim Davis style, bold colors, heavy eyelids, striped cat, lasagna." },
    { name: "Archie Comics Retro", description: "Dan DeCarlo style, idealized 50s teens, clean lines, simple coloring." },
    { name: "Scott Pilgrim Indie", description: "Manga influence, bold thick outlines, video game logic, flat graphical style." },
    { name: "Manga Black & White", description: "Pen and ink, screentones (dots/lines) for shading, speed lines, sound effects." },
    { name: "Webtoon Manhwa Color", description: "Digital painting, vertical composition, polished lighting, attractive characters." }
  ],
  "Video Game Worlds": [
    { name: "Minecraft Voxel", description: "Everything made of cubes, pixel textures on 3D blocks, grid alignment." },
    { name: "Roblox Avatar", description: "Blocky simple character mesh, plastic texture, accessories, simple face decal." },
    { name: "Fortnite Stylized 3D", description: "Vibrant colors, slightly exaggerated proportions, clean textures, no noise, rim lighting." },
    { name: "Mario 3D World", description: "Rounded friendly shapes, bright primary colors, plastic/shiny textures, nintendo polish." },
    { name: "Sonic the Hedgehog", description: "Yuji Uekawa style, bold outlines, attitude poses, rubber hose limbs, spikes." },
    { name: "Pokemon Sugimori Art", description: "Ken Sugimori watercolor style (original) or clean digital vector (modern), anime eyes." },
    { name: "Animal Crossing Villager", description: "Felt/flock texture, round shapes, pastel colors, cozy aesthetic." },
    { name: "Zelda Breath of the Wild", description: "Cel-shaded characters, painterly environments, soft lighting, wispy effects." },
    { name: "Dark Souls Gothic", description: "Decaying armor, fog, muted dark colors, intricate details, depressing atmosphere." },
    { name: "Cyberpunk 2077 Glitch", description: "Yellow UI elements, digital artifacts, chromatic aberration, futuristic grime." },
    { name: "GTA Loading Screen", description: "Vectorized realism, heavy black outlines, digital airbrush shading, mural style." },
    { name: "Fallout Vault Boy", description: "1950s cartoon mascot style, simple lines, blonde hair, thumbs up." },
    { name: "Doom Slayer Heavy Metal", description: "Green armor, demons, gore, heavy contrast, mars atmosphere." },
    { name: "League of Legends Splash", description: "High fidelity digital painting, dramatic lighting, action pose, detailed rendering." },
    { name: "Overwatch Hero Style", description: "Pixar-meets-anime, clean sci-fi textures, distinct silhouettes, polished." }
  ],
  "Retro Nostalgia": [
    { name: "80s Neon Retrowave", description: "Outrun aesthetic, wireframe grid landscape, purple/cyan gradient, chrome text, sunset." },
    { name: "90s Saved by the Bell Memphis", description: "Abstract geometric shapes, squiggles, triangles, confetti pattern, bright pastel neon." },
    { name: "Y2K Chrome & Bling", description: "Year 2000 aesthetic, liquid chrome blobs, icy blue, futuristic curves, shiny plastic." },
    { name: "70s Flower Power Disco", description: "Groovy bulbous fonts, orange/brown/yellow palette, paisley patterns, flowers." },
    { name: "50s Diner & Rockabilly", description: "Checkered floors, cherry red, chrome trim, milkshake aesthetic, jukebox." },
    { name: "Victorian Steampunk", description: "Sepia tones, gears, brass, corsets, goggles, steam power." },
    { name: "Roaring 20s Art Deco", description: "Black and gold, geometric fans, sunbursts, luxury, great gatsby style." },
    { name: "Vintage Travel Poster", description: "WPA style, flat colors, screen print look, scenic landscapes, bold typography." },
    { name: "Propaganda Poster Style", description: "Constructivist design, red/black/cream, bold angles, heroic poses, rays of light." },
    { name: "Vintage Glamour Art (Pinup)", description: "Gil Elvgren style, oil painting, idealized beauty, soft lighting, cheeky poses." },
    { name: "Kodak Film Photography", description: "Warm colors, film grain, light leaks, disposable camera aesthetic, nostalgia." },
    { name: "VHS Tape Static", description: "Tracking lines, color noise, scanlines, blurry text, low resolution." },
    { name: "Arcade Cabinet Art", description: "Airbrushed sci-fi scenes, chrome robots, space battles, vibrant colors." },
    { name: "Floppy Disk Aesthetic", description: "Beige plastic, handwritten labels, magnetic tape, low-tech office vibes." },
    { name: "Tamagotchi Pixel", description: "1-bit monochrome pixel art, LCD screen ghosting, simple cute sprites." }
  ],
  "Abstract & Geometric": [
    { name: "Fractal Geometry", description: "Mandelbrot sets, infinite self-similar complexity, mathematical patterns, psychedelic colors." },
    { name: "Kaleidoscope Pattern", description: "Radial symmetry, mirrored segments, colorful glass shards, geometric complexity." },
    { name: "Low Poly Mesh", description: "3D model with visible triangular facets, flat shading, no smoothing, geometric look." },
    { name: "Voxel Block Art", description: "3D pixels (cubes), magica voxel style, isometric view, blocky rendering." },
    { name: "Fluid Acrylic Pour", description: "Marbled liquid paint, cells, mixing colors, organic flow, abstract expressionism." },
    { name: "Mandala Intricate", description: "Circular spiritual diagram, fine line detail, radial balance, meditative pattern." },
    { name: "Bauhaus Geometric", description: "Minimalist, primary colors, simple shapes (circle, square, triangle), asymmetry." },
    { name: "Cubist Fragmentation", description: "Picasso style, shattered planes, multiple viewpoints, flat shapes, abstract." },
    { name: "Optical Illusion (Op Art)", description: "Black and white contrasting patterns, vibrating effect, bridget riley style." },
    { name: "Minimalist Line Art", description: "Single continuous line drawing, negative space, abstract faces/shapes, clean." },
    { name: "Splatter Painting", description: "Jackson Pollock style, chaotic drips, fling paint, energetic action." },
    { name: "Alcohol Ink Swirls", description: "Translucent dyes, ethereal wisps, gold veins, fluid organic shapes." },
    { name: "Paper Quilling", description: "Rolled strips of paper, edge-on view, delicate spirals, shadow depth." },
    { name: "Origami Folded", description: "Geometric paper planes, sharp creases, paper texture, angular forms." },
    { name: "Mosaic Tile", description: "Small colored stones/glass, grout lines, fragmented image, classical style." }
  ],
  "Nature & Wildlife": [
    { name: "National Park Badge", description: "Vector patch style, thick borders, scenic landscape layers, retro typography." },
    { name: "Scientific Botanical Illustration", description: "Vintage 19th-century scientific lithograph style, highly detailed stipple engraving, hand-colored with watercolor wash, antique paper texture, latin labels, botanical accuracy, isolated on white." },
    { name: "Audubon Bird Painting", description: "John James Audubon style, life-size realism, watercolor and pastel, dramatic pose, white background." },
    { name: "Realistic Wildlife Oil", description: "Detailed fur texture, lifelike eyes, soft focus background, wildlife photography style." },
    { name: "Macro Insect Photography", description: "Extreme closeup, compound eyes visible, shallow depth of field, iridescent exoskeleton." },
    { name: "Undersea Marine Life", description: "Coral reef colors, fish scales, blue water gradients, caustic light patterns." },
    { name: "Jungle / Tropical Leaf", description: "Monstera, palm fronds, vibrant greens, dense foliage pattern, botanical." },
    { name: "Desert Cacti & Skull", description: "Succulents, saguaro, bleached bones, warm sand tones, western vibe." },
    { name: "Mushroom / Mycology", description: "Detailed fungi illustration, forest floor, moss, fairy core aesthetic." },
    { name: "Crystal & Gemstone", description: "Geological illustration, faceted minerals, sparkle, watercolor texture." },
    { name: "Galaxy & Nebula", description: "Space gas clouds, stars, purple/blue/pink gradients, cosmic dust." },
    { name: "Aurora Borealis", description: "Northern lights, green and purple ribbons, night sky, silhouette trees." },
    { name: "Mountain Landscape", description: "Snowy peaks, atmospheric perspective, bob ross style oil painting." },
    { name: "Beach / Surf Vibe", description: "Crashing waves, sand texture, palm trees, sunny summer colors." },
    { name: "Rainforest Frog", description: "Brightly colored poison dart frog, wet skin texture, exotic nature." }
  ],
  "Food & Culinary": [
    { name: "Gourmet Burger Photography", description: "Food stylist photography, macro lens, juicy patty, melting cheese, sesame bun, glistening." },
    { name: "Sushi Platter Art", description: "Fresh fish texture, rice grains, vibrant colors, artistic arrangement, japanese ceramic." },
    { name: "Ramen Bowl Illustration", description: "Top down or isometric, noodle texture, steam rising, soft boiled egg, rich broth." },
    { name: "Donut with Sprinkles", description: "Pink strawberry frosting, colorful sprinkles, fried dough texture, simpsons vibe." },
    { name: "Melting Ice Cream", description: "Soft serve swirl, dripping liquid, waffle cone texture, summer vibe." },
    { name: "Pizza Slice Cartoon", description: "Gooey cheese stretch, pepperoni, greasy, ninja turtles style." },
    { name: "Taco Truck Art", description: "Street food aesthetic, corn tortilla texture, cilantro, lime, vibrant colors." },
    { name: "French Pastry Watercolor", description: "Delicate macarons, croissants, flaky texture, soft pastel colors." },
    { name: "Candy Wrapper Pop Art", description: "Crinkled plastic texture, bright logos, warhol style, sugar rush." },
    { name: "Fruit Pattern Print", description: "Repeating lemons/cherries/strawberries, flat vector, textile design." },
    { name: "Cheese & Wine", description: "Charcuterie board, wood texture, grapes, variety of cheeses, elegant." },
    { name: "BBQ Smokehouse", description: "Ribs, grill marks, smoke effects, savory colors, sauce drip." },
    { name: "Kawaii Bento Box", description: "Food arranged like cute animals, rice balls with faces, compartmentalized." },
    { name: "Gingerbread Man", description: "Cookie texture, white icing piping, gumdrop buttons, holiday vibe." },
    { name: "Chili Pepper Fire", description: "Glossy red pepper, flames, heat waves, spicy mascot." }
  ],
  "Fashion & Style": [
    { name: "Sneakerhead High Top", description: "Detailed sneaker vector, side profile, laces, leather texture, street culture." },
    { name: "Denim Patchwork", description: "Blue jean fabric texture, stitching details, frayed edges, layered patches." },
    { name: "Leather Jacket Biker", description: "Black leather texture, silver zippers, studs, rebellion aesthetic." },
    { name: "Haute Couture Sketch", description: "Fashion design illustration, elongated croquis figure, fabric movement, marker rendering." },
    { name: "Streetwear Hypebeast", description: "Oversized hoodie, brand logos, camouflage pattern, urban fashion." },
    { name: "Vintage Thrift Shop", description: "Flannel patterns, corduroy texture, retro dad hat, 90s vibe." },
    { name: "Jewelry & Diamonds", description: "Vectorized gemstones, gold chains, sparkle effects, luxury." },
    { name: "Makeup Artistry", description: "Lipstick smear texture, eyeshadow palette, mascara wand, cosmetic illustration." },
    { name: "Barber Shop Pole", description: "Red white blue stripes, spinning motion blur, vintage chrome." },
    { name: "T-Shirt Graphic Design", description: "Screen print texture, distressed ink, band tee aesthetic." },
    { name: "Boho Chic Floral", description: "Flowy fabric, flower crowns, paisley, earth tones, coachella vibe." },
    { name: "Goth Platform Boot", description: "Thick rubber soles, buckles, black leather, stomper boots." },
    { name: "Preppy Pastel", description: "Polo shirts, cable knit sweaters, soft pinks and blues." },
    { name: "Techwear Ninja", description: "Black straps, buckles, matte fabric, cyberpunk fashion." },
    { name: "Cosplay Armor", description: "EVA foam texture, battle damage, fantasy costume design." }
  ],
  "Vehicles & Transport": [
    { name: "JDM Tuner Car", description: "Japanese sports car, wide body kit, spoiler, drifting smoke, neon underglow." },
    { name: "American Muscle Hot Rod", description: "V8 engine, blower, flames paint job, chrome wheels, aggressive stance." },
    { name: "Vintage Vespa Scooter", description: "Italian retro style, pastel color, curvy chassis, mod culture." },
    { name: "Harley Davidson Chopper", description: "Long forks, ape hanger bars, v-twin engine, chrome and leather." },
    { name: "F1 Race Car", description: "Open wheel aerodynamic design, sponsorship decals, speed blur." },
    { name: "Steam Locomotive Train", description: "Iron beast, smoke stack, connecting rods, wild west era." },
    { name: "Space Shuttle / Rocket", description: "NASA white, blast off flames, smoke plume, space exploration." },
    { name: "Sailboat / Yacht", description: "White triangular sails, blue water hull, nautical ropes, luxury." },
    { name: "UFO Flying Saucer", description: "Metallic disc, dome top, beam of light, 50s sci-fi style." },
    { name: "Monster Truck", description: "Giant tires, suspension, crushing car underneath, mud splatter." },
    { name: "Skateboard Deck", description: "Wooden ply texture, grip tape, wheels and trucks, bottom graphic." },
    { name: "BMX Bike", description: "Chromoly frame, mag wheels, handlebar pads, stunt pose." },
    { name: "Private Jet", description: "Sleek aerodynamics, small windows, flying high." },
    { name: "Submarine Steampunk", description: "Brass hull, portholes, rivets, propeller, underwater." },
    { name: "School Bus", description: "Classic yellow, stop sign, black stripes, childhood nostalgia." }
  ],
  "Professions & Hobbies": [
    { name: "Software Developer Code", description: "Monospace font, syntax highlighting colors, IDE interface, matrix background." },
    { name: "Artist Paint Palette", description: "Wooden palette shape, blobs of oil paint, mixing colors, messy." },
    { name: "Chef Knife & Hat", description: "Stainless steel blade reflection, white toque, culinary arts." },
    { name: "Gamer Controller", description: "Gamepad shape, colored buttons, joysticks, plastic texture." },
    { name: "Photographer Camera", description: "DSLR lens glass reflection, aperture blades, camera body." },
    { name: "Mechanic Wrench", description: "Grease stains, chrome tools, nuts and bolts." },
    { name: "Doctor Stethoscope", description: "Medical tubing, metal chest piece, heartbeat line." },
    { name: "Writer Typewriter", description: "Vintage keys, paper roller, ink ribbon, classic author vibe." },
    { name: "Musician Guitar", description: "Electric guitar body, strings, pickups, rock n roll." },
    { name: "Scientist Beaker", description: "Erlenmeyer flask, bubbling liquid, safety goggles." },
    { name: "Gardener Trowel", description: "Garden tool, soil, potted plant, green thumb." },
    { name: "Astronaut Helmet", description: "Bubble visor, reflection of earth, space suit collar." },
    { name: "Firefighter Axe", description: "Red handle, sharp blade, maltese cross symbol." },
    { name: "Police Badge", description: "Gold or silver shield, engraved text, authority." },
    { name: "Teacher Apple", description: "Red delicious apple, worm, ruler, chalkboard background." }
  ],
  "Sports & Action": [
    { name: "Basketball Slam Dunk", description: "Silhouette or detailed player, ball in net, shattered backboard effect." },
    { name: "Soccer / Football Crest", description: "Shield shape, team colors, ball icon, ribbon text." },
    { name: "American Football Helmet", description: "Gridiron helmet, facemask, glossy team colors, side view." },
    { name: "Baseball Card Style", description: "Portrait of player, stats border, team logo cap." },
    { name: "Surfing Wave", description: "Curling wave barrel, surfer on board, water spray." },
    { name: "Skateboarding Trick", description: "Mid-air kickflip, deck graphic visible, dynamic angle." },
    { name: "Snowboarding Gear", description: "Reflective goggles, beanie, snow spray, winter vibes." },
    { name: "Boxing Gloves", description: "Red leather texture, laces, impact starburst." },
    { name: "Yoga / Meditation", description: "Lotus pose silhouette, mandala background, peaceful gradient." },
    { name: "Gym / Bodybuilding", description: "Dumbbell, flexing arm, vein detail, motivational vibe." },
    { name: "Tennis Racket", description: "String grid, fuzzy yellow ball, motion blur swing." },
    { name: "Golf Club", description: "Iron or driver head, golf ball on tee, green grass." },
    { name: "F1 Checkered Flag", description: "Waving black and white flag, speed lines, racing." },
    { name: "Motocross Dirt Bike", description: "Rider in air, mud flying, helmet and goggles." },
    { name: "Rock Climbing", description: "Carabiner, climbing rope, chalk bag, jagged rock face." }
  ],
  "Holidays & Seasons": [
    { name: "Halloween Pumpkin", description: "Carved jack-o-lantern face, candle light inside, orange and black." },
    { name: "Christmas Ornament", description: "Shiny glass bauble, reflection, metal hook, evergreen branch." },
    { name: "Valentine's Heart", description: "Classic red heart shape, cupid arrow, lace border." },
    { name: "Easter Bunny", description: "Cute rabbit, painted eggs, pastel spring colors." },
    { name: "St Patrick's Clover", description: "Four leaf clover, green and gold, celtic knot." },
    { name: "Thanksgiving Turkey", description: "Cooked turkey on platter or cartoon live bird, autumn leaves." },
    { name: "4th of July Fireworks", description: "Bursting star shell, red white and blue, night sky." },
    { name: "Chinese New Year Dragon", description: "Traditional parade puppet, red and gold, festive." },
    { name: "Dia de los Muertos", description: "Sugar skull, marigold flowers, colorful patterns." },
    { name: "Summer Vacation", description: "Sun wearing sunglasses, pool float, ice cream." },
    { name: "Winter Snowflake", description: "Intricate ice crystal geometry, blue and white." },
    { name: "Spring Flower", description: "Blooming tulip or daisy, green stem, fresh dew." },
    { name: "Autumn Leaf", description: "Maple leaf, gradient red orange yellow, crunchy texture." },
    { name: "Birthday Cake", description: "Layer cake, frosting, lit candles, confetti." },
    { name: "Wedding Ring", description: "Diamond solitaire, gold band, sparkle." }
  ],
  "Cute & Kawaii": [
    { name: "Hello Kitty Style", description: "Sanrio style, simple outlines, no mouth, bow, cute pose." },
    { name: "Pusheen Cat Style", description: "Chubby grey tabby, simple face, wobbly lines, snacks." },
    { name: "Rilakkuma Bear", description: "Relaxed brown bear, simple face, zipper on back." },
    { name: "Tamagotchi Pixel", description: "LCD screen texture, monochrome pixel pet, egg shape." },
    { name: "Pastel Goth", description: "Spooky subjects (bats/skulls) in cute pastel pink colors." },
    { name: "Furry Art Style", description: "Anthropomorphic animal, big expressive eyes, fluffy texture." },
    { name: "Chibi Anime Character", description: "2-heads tall, giant head, tiny body, blushing cheeks." },
    { name: "Food with Faces", description: "Inanimate food items with cute smiley faces." },
    { name: "Baby Animal Realism", description: "Kitten or puppy, big eyes, soft fur, innocent look." },
    { name: "Unicorn Rainbow", description: "White horse, horn, rainbow mane, sparkles, clouds." },
    { name: "Mermaid Princess", description: "Cute tail, shell bra, underwater bubbles, flowing hair." },
    { name: "Fairy Dust", description: "Tiny wings, glowing wand, magical sparkles." },
    { name: "Squishmallow", description: "Ultra round shape, simple embroidered face, soft plush texture." },
    { name: "Bubble Tea", description: "Cute cup with face, tapioca pearls, pastel straw." },
    { name: "Emoji Face", description: "Yellow circle, expressive face, chat bubble aesthetic." }
  ],
  "Materials & Textures": [
    { name: "Liquid Chrome", description: "Highly reflective silver metal, distorted environment reflection, fluid shape." },
    { name: "Holographic Foil", description: "Rainbow spectrum reflection, metallic silver base, iridescent." },
    { name: "Gold Leaf Flakes", description: "Rich metallic yellow gold, textured foil edges, luxury." },
    { name: "Rusty Metal", description: "Corroded iron, orange rust texture, industrial decay." },
    { name: "Rough Concrete", description: "Grey cement texture, pockmarks, industrial brutalism." },
    { name: "Polished Marble", description: "White stone, grey veins, glossy surface, classical." },
    { name: "Knitted Wool", description: "Interlocking loops of yarn, cozy texture, fabric detail." },
    { name: "Denim Fabric", description: "Blue indigo weave, white thread stitching, texture." },
    { name: "Leather Grain", description: "Black animal hide texture, pores, sheen." },
    { name: "Carbon Fiber", description: "Black woven pattern, high tech, automotive." },
    { name: "Slime / Ooze", description: "Translucent green liquid, drips, bubbles, glossy." },
    { name: "Bubble Wrap", description: "Plastic air pockets, transparency, highlight reflections." },
    { name: "Broken Glass", description: "Sharp shards, cracks, refraction, dangerous." },
    { name: "Neon Glow", description: "Bright colored light source, bloom effect, dark background." },
    { name: "Vantablack Void", description: "Pure black silhouette, no internal detail, absorbs light." }
  ],
  "Typography & Lettering": [
    { name: "Graffiti Tagging", description: "Marker or spray paint signature, drips, street style." },
    { name: "Elegant Calligraphy", description: "Copperplate script, thick and thin strokes, flourishes." },
    { name: "Neon Sign Text", description: "Connected glass tubes, glowing gas, electric colors." },
    { name: "Vintage Sign Painting", description: "Hand painted serif, drop shadow, gold leaf outline." },
    { name: "Typewriter Font", description: "Courier letters, ink bleed, uneven alignment." },
    { name: "Ransom Note Cutout", description: "Mismatched magazine letters, torn paper edges." },
    { name: "Comic Book Sound Effect", description: "Bold block letters, 3D extrusion, action burst." },
    { name: "Gothic Blackletter", description: "Old English style, sharp angles, medieval manuscript." },
    { name: "Bubble Letters", description: "Round puffy font, highlights, graffiti throw-up style." },
    { name: "Pixel Font", description: "Blocky jagged edges, retro computer screen." },
    { name: "Serif Book Font", description: "Times New Roman style, clean, academic." },
    { name: "Sans Serif Minimal", description: "Helvetica style, modern, bold, clean edges." },
    { name: "Chalkboard Menu", description: "White powdery chalk texture, black slate background." },
    { name: "Letterpress Texture", description: "Debossed letters into paper, shadow depth, ink texture." },
    { name: "Monogram Logo", description: "Interlocking initials, vector shape, branding." }
  ]
};
